name: Build Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Deploy artifacts to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: godot-gameplay-tags.ubuntu
        path: |
          godot/addons/godot_gameplay_tags/godot_gameplay_tags.gdextension
          godot/addons/godot_gameplay_tags/build/*/godot_gameplay_tags.*
  
  build_macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Deploy artifacts to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: godot-gameplay-tags.macos
        path: |
          godot/addons/godot_gameplay_tags/godot_gameplay_tags.gdextension
          godot/addons/godot_gameplay_tags/build/*/godot_gameplay_tags.*

  build_windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Deploy artifacts to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: godot-gameplay-tags.windows
        path: |
          godot/addons/godot_gameplay_tags/godot_gameplay_tags.gdextension
          godot/addons/godot_gameplay_tags/build/*/godot_gameplay_tags.dll